/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.terminal;

import org.terminal.console.api.ConsoleImpl;

public final class Window {
    public static final ConsoleImpl console = null;
}
