/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.terminal;

import org.terminal.console.api.Console;

public final class Window {
    public static final Console console = null;
}
